name: 'data_diff'
config-version: 2

model-paths: ["models"]
macro-paths: ["macros"]

clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

vars:
  data_diff__on_migration: false # Enable to deploy the package's resources e.g. stored proc, take precedence to `data_diff__on_migration_data`
  data_diff__on_migration_data: false # Enable to refresh the list of tables configured for the validation
  data_diff__on_run_hook: false # Enable to run data diff's hook
  # data_diff__database: COMMON
  # data_diff__schema: DATA_DIFF

  # data_diff__configured_tables__source_fixed_naming: true
  #                                     # Set false to let (only) source db & schema naming follow the configured one in dbt
  #                                     # we always expect the target is fixed to Prod for example
  # data_diff__configured_tables__target_fixed_naming: true
  #                                     # same as above but for the target
  # data_diff__configured_tables:
  #   - src_db: src_db                  # optional, empty to get target.database
  #     src_schema: src_schema          # optional, empty to get target.schema
  #     src_table: table1               # mandatory
  #     trg_db: trg_db                  # optional, empty to get target.database
  #     trg_schema: trg_schema          # optional, empty to get target.schema
  #     trg_table: table1               # optional, empty to get src_table
  #     pk: key                         # mandatory, multiple columns splitted by comma e.g. key1,key2
  #     include_columns: []             # optional, [] to include all
  #     exclude_columns: ["timestamp"]  # optional, [] to exclude nothing
  #     where: "1=1"                    # optional, [] to exclude nothing
  #     pipe_name: ''                   # optional, 1=1 by default
  #                                     # in non-async mode, it must be empty if specified
  #                                     # in async mode, it can be any value e.g. "1", "batch_dat", "batch_milan"

  # data_diff__key_check_summary__alias: report_of_key_check
  # data_diff__key_check__alias: result_of_key_check
  # data_diff__schema_check_summary__alias: report_of_schema_check
  # data_diff__schema_check__alias: result_of_schema_check
  # data_diff__data_diff_check__alias: result_of_data_diff_check
  # data_diff__configured_tables__alias: tables_to_validate
  # data_diff__log_for_validation__alias: log_for_validation

on-run-end:
  - > # migration hook
    {% if var("data_diff__on_migration", false) %}
      {{ data_diff.create_resources() }}

      {% if execute and var("data_diff__on_migration_data", true) %}
        {{ data_diff.refresh_configured_tables() }}
      {% endif %}

    {% endif %}
