name: 'data_diff'
config-version: 2

model-paths: ["models"]
macro-paths: ["macros"]

clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

vars:
  data_diff__on_migration: false # Enable to release the package's resources e.g. stored proc, take precedence to `data_diff__on_migration_data`
  data_diff__on_migration_data: false # Enable to refresh the list of tables configured for the validation
  data_diff__on_run_hook: false # Enable to run data diff as dbt hook
  # data_diff__database: COMMON
  # data_diff__schema: DATA_DIFF

  # data_diff__configured_tables:
  #   - src_db: src_db
  #     src_schema: src_schema
  #     src_table: table1
  #     trg_db: trg_db
  #     trg_schema: trg_schema
  #     trg_table: table1
  #     pk: key
  #     include_columns: [] # [] to include all
  #     exclude_columns: ["timestamp"] # [] to exclude nothing
  #     batch: '' # optional, empty by default
  #               # in non-async mode, it must be empty if specified
  #               # in async mode, it can be any value e.g. "1", "batch_dat", "batch_milan"

  # data_diff__key_check_summary__alias: report_of_key_check
  # data_diff__key_check__alias: result_of_key_check
  # data_diff__schema_check_summary__alias: report_of_schema_check
  # data_diff__schema_check__alias: result_of_schema_check
  # data_diff__data_diff_check__alias: result_of_data_diff_check
  # data_diff__configured_tables__alias: tables_to_validate
  # data_diff__log_for_validation__alias: log_for_validation

on-run-end:
  - > # migration hook
    {% if var("data_diff__on_migration", false) %}
      {{ data_diff.create_resources() }}

      {% if execute and var("data_diff__on_migration_data", true) %}
        {{ data_diff.refresh_configured_tables() }}
      {% endif %}

    {% endif %}
  - > # run data-diff hook
    {% if var("data_diff__on_run_hook", false) %}
      {{ data_diff.data_diff__run(in_hook=true) }}
    {% endif %}
