name: 'data_diff_test'
version: '0.0.0'
config-version: 2

profile: 'data_diff'

clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

vars:
  data_diff__database: data_diff
  data_diff__schema: common
  # For normal (non-async) mode
  data_diff__configured_tables:
    - # src_db: data_diff
      src_schema: blue_dat
      src_table: my_first_dbt_model
      # trg_db: data_diff
      trg_schema: green_dat
      trg_table: my_first_dbt_model
      pk: id # id1,id2
      include_columns: []
      exclude_columns: ["loaded_at"]
      # pipe_name: awesome_thread
    - src_schema: blue_dat
      src_table: my_second_dbt_model
      trg_schema: green_dat
      trg_table: my_second_dbt_model
      pk: id
      include_columns: []
      exclude_columns: ["loaded_at"]
  # data_diff__auto_pipe: true
