name: testing on pull request

on:
  pull_request:
    branches: [ "main" ]

jobs:
  snowflake:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        adapter: ["snowflake"]
        version: ["1.7.1"]
    container:
      image: "ghcr.io/dbt-labs/dbt-${{ matrix.adapter }}:${{ matrix.version }}"
    steps:
      - uses: actions/checkout@v3

      - name: Run integration test
        run: |
          TODO
        env:
          DBT_SNOWFLAKE_TEST_ACCOUNT: ${{ secrets.DBT_SNOWFLAKE_TEST_ACCOUNT }}
          DBT_SNOWFLAKE_TEST_USER: ${{ secrets.DBT_SNOWFLAKE_TEST_USER }}
          DBT_ENV_SECRET_SNOWFLAKE_TEST_PASSWORD: ${{ secrets.DBT_ENV_SECRET_SNOWFLAKE_TEST_PASSWORD }}
          DBT_SNOWFLAKE_TEST_ROLE: ${{ secrets.DBT_SNOWFLAKE_TEST_ROLE }}
          DBT_SNOWFLAKE_TEST_DATABASE: ${{ secrets.DBT_SNOWFLAKE_TEST_DATABASE }}
          DBT_SNOWFLAKE_TEST_WAREHOUSE: ${{ secrets.DBT_SNOWFLAKE_TEST_WAREHOUSE }}
          DBT_SCHEMA: PRCI_${{ matrix.version }}_${{ github.sha }}
